### ISSUE TITLE
Bug: No longer allows cross Testnet/Mainnet queries

### ISSUE THREAD

**Issue by awmuncy** [tablelandnetwork/table-nft-renderer#27]
I believe this is due to Validator/SDK updates, though I could be wrong.

**Comment by carsonfarmer** [comment]
The refactored SDK (will have, I mean, it has them, but it isn't published) helper functions for getBaseUrl, getChainId, getContractAddress, and others. We could probably also have some helpers explicitly for whether it is a 'testnet' or 'mainnet'?

**Comment by carsonfarmer** [comment]
With all of that in mind, even with the current parser and sdk, the above information can be extracted. Normalizing a statement can be used to extract the table name, and validateTableName can be used to extract the chainId, etc. Then you simply create a helper function of your own (just for now) that switches on this and returns 'testnet' or 'mainnet' as needed.

**Comment by carsonfarmer** [comment]
But again, if we can hold off a bit, then we can get all this "for free" via the SDK, because the SDK needs to know all this to route queries appropriately anyway.
